project 'PoliteBooks.xcodeproj'
 
target 'PoliteBooks' do
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'YYModel'
  pod 'HHTransition', '~> 1.2.0'
  pod 'JQFMDB'
  pod 'BmobSDK'
end
